package ua.andre.libraryapp.models;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;

//create table "user"(
//        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        "name" varchar NOT NULL CHECK (LENGTH("name") BETWEEN 2 AND 30),
//        surname varchar NOT NULL CHECK (LENGTH(surname) BETWEEN 2 AND 30),
//        age int check (age > 0)
//        )

public class User {

    private int id;

    @NotEmpty(message = "Name should not be empty!")
    @Size(min = 2, max = 30, message = "Name should be between 2 and 30 characters!")
    private String name;

    @NotEmpty(message = "Surname should not be empty!")
    @Size(min = 2, max = 30, message = "Surname should be between 2 and 30 characters!")
    private String surname;

    @NotEmpty(message = "Age should not be empty!")
    @Min(value = 0, message = "Age should be greater than zero!")
    private int age;

    public User() {
    }

    public User(int id, String name, String surname, int age) {
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.age = age;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}

//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Alice', 'Johnson', 22);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Bob', 'Smith', 35);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Charlie', 'Williams', 41);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('David', 'Brown', 28);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Emma', 'Taylor', 19);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Frank', 'Anderson', 56);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Grace', 'Martinez', 33);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Henry', 'Davis', 48);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Isabella', 'Wilson', 27);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Jack', 'Thomas', 23);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Kate', 'Lee', 37);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Liam', 'Garcia', 45);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Mia', 'Rodriguez', 20);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Noah', 'Hernandez', 29);
//    INSERT INTO "user" ("name", "surname", "age") VALUES ('Olivia', 'Lopez', 31);